site_name: fabrika-platform
site_url: https://platform.fabrika.digital
theme:
  name: material
  language: en
  logo: images/fabrika logo_250_white
  favicon: fabrika logo_favicon
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fabrika-platform
    - icon: fontawesome/solid/envelope
      link: mailto:info@fabrika.digital
  canonical_url: https://platform.fabrika.digital
  generator: false
plugins:
  - search
  - macros
  - redirects

extra_javascript: []
extra_css: []
extra_templates: []
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Hardware:
      - openHMI: hardware/openhmi.md
      - Teledriver: hardware/teledriver.md
      - ekoenergo: ekoenergo.md
      - Controls: hardware/Controls/Controls.md
      - Displays: hardware/Displays/Displays.md
      - Displays:
        - stepHMI: hardware/Displays/stepHMI/stepHMI.md
      - Drives: hardware/Drives/Drives.md
  - Software:
      - Firmware: software/firmware.md
      - API: software/api.md

